# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.models.eco_web_server_data_transfer_objects_user_dto import EcoWebServerDataTransferObjectsUserDTO  # noqa: E501
from ecoserver.rest import ApiException


class TestEcoWebServerDataTransferObjectsUserDTO(unittest.TestCase):
    """EcoWebServerDataTransferObjectsUserDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcoWebServerDataTransferObjectsUserDTO(self):
        """Test EcoWebServerDataTransferObjectsUserDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ecoserver.models.eco_web_server_data_transfer_objects_user_dto.EcoWebServerDataTransferObjectsUserDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
