# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.law_api import LawApi  # noqa: E501
from ecoserver.rest import ApiException


class TestLawApi(unittest.TestCase):
    """LawApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.law_api.LawApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_law_generate_test_data(self):
        """Test case for law_generate_test_data

        Genereate test laws.  # noqa: E501
        """
        pass

    def test_law_get_district_map(self):
        """Test case for law_get_district_map

        """
        pass

    def test_law_get_law(self):
        """Test case for law_get_law

        Returns the law with the specified id.  # noqa: E501
        """
        pass

    def test_law_list(self):
        """Test case for law_list

        Returns all laws currently present in the game in the specified states, active by default.  # noqa: E501
        """
        pass

    def test_law_list_all(self):
        """Test case for law_list_all

        Returns all laws currently present in the game  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
