# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.models.eco_web_server_data_transfer_objects_chat_message_dto import EcoWebServerDataTransferObjectsChatMessageDTO  # noqa: E501
from ecoserver.rest import ApiException


class TestEcoWebServerDataTransferObjectsChatMessageDTO(unittest.TestCase):
    """EcoWebServerDataTransferObjectsChatMessageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcoWebServerDataTransferObjectsChatMessageDTO(self):
        """Test EcoWebServerDataTransferObjectsChatMessageDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ecoserver.models.eco_web_server_data_transfer_objects_chat_message_dto.EcoWebServerDataTransferObjectsChatMessageDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
