# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.models.system_numerics_vector3 import SystemNumericsVector3  # noqa: E501
from ecoserver.rest import ApiException


class TestSystemNumericsVector3(unittest.TestCase):
    """SystemNumericsVector3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemNumericsVector3(self):
        """Test SystemNumericsVector3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ecoserver.models.system_numerics_vector3.SystemNumericsVector3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
