# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.map_api import MapApi  # noqa: E501
from ecoserver.rest import ApiException


class TestMapApi(unittest.TestCase):
    """MapApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.map_api.MapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_map_entities(self):
        """Test case for map_entities

        Allows access to all entities currently available in the simulation.  # noqa: E501
        """
        pass

    def test_map_entity_types(self):
        """Test case for map_entity_types

        Allows access to all species currently available in the simulation.  # noqa: E501
        """
        pass

    def test_map_get_dimension(self):
        """Test case for map_get_dimension

        Returns the dimension of the world, in blocks.  # noqa: E501
        """
        pass

    def test_map_get_property(self):
        """Test case for map_get_property

        """
        pass

    def test_map_layer_list(self):
        """Test case for map_layer_list

        List Layer Names.  # noqa: E501
        """
        pass

    def test_map_make_map_json(self):
        """Test case for map_make_map_json

        One request to get all required web map data.  # noqa: E501
        """
        pass

    def test_map_map_stats(self):
        """Test case for map_map_stats

        """
        pass

    def test_map_water_level(self):
        """Test case for map_water_level

        Get water height.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
