# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.command_api import CommandApi  # noqa: E501
from ecoserver.rest import ApiException


class TestCommandApi(unittest.TestCase):
    """CommandApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.command_api.CommandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_command_exec_command(self):
        """Test case for command_exec_command

        Executes a chat command on the server.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
