# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.chat_api import ChatApi  # noqa: E501
from ecoserver.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.chat_api.ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chat_get_chat(self):
        """Test case for chat_get_chat

        Returns all non-private player chat messages sent within the given time range.  # noqa: E501
        """
        pass

    def test_chat_get_chat_by_tag(self):
        """Test case for chat_get_chat_by_tag

        Returns all non-private player chat messages sent to the given tag within the given time range.  # noqa: E501
        """
        pass

    def test_chat_get_chat_messages_sent_by(self):
        """Test case for chat_get_chat_messages_sent_by

        Returns all non-private chat messages sent by the given user within the given time range.  # noqa: E501
        """
        pass

    def test_chat_get_next(self):
        """Test case for chat_get_next

        Gets the. <code>numNextMessages</code> chat messages sent after the given message on the same tag.  # noqa: E501
        """
        pass

    def test_chat_get_previous(self):
        """Test case for chat_get_previous

        Gets the. <code>numPreviousMessages</code> chat messages sent before the given message on the same tag.  # noqa: E501
        """
        pass

    def test_chat_send_chat(self):
        """Test case for chat_send_chat

        Sends chat message like username.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
