# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.admin_api import AdminApi  # noqa: E501
from ecoserver.rest import ApiException


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.admin_api.AdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_get_get_access(self):
        """Test case for admin_get_get_access

        """
        pass

    def test_admin_get_get_server_name(self):
        """Test case for admin_get_get_server_name

        """
        pass

    def test_admin_post_game_export(self):
        """Test case for admin_post_game_export

        """
        pass

    def test_admin_post_set_access(self):
        """Test case for admin_post_set_access

        Sets how accessible this server is.  # noqa: E501
        """
        pass

    def test_admin_post_set_server_name(self):
        """Test case for admin_post_set_server_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
