# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.models.eco_shared_items_proposable_state import EcoSharedItemsProposableState  # noqa: E501
from ecoserver.rest import ApiException


class TestEcoSharedItemsProposableState(unittest.TestCase):
    """EcoSharedItemsProposableState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEcoSharedItemsProposableState(self):
        """Test EcoSharedItemsProposableState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ecoserver.models.eco_shared_items_proposable_state.EcoSharedItemsProposableState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
