# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.plugins_api import PluginsApi  # noqa: E501
from ecoserver.rest import ApiException


class TestPluginsApi(unittest.TestCase):
    """PluginsApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.plugins_api.PluginsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_plugins_get_plugin_config(self):
        """Test case for plugins_get_plugin_config

        """
        pass

    def test_plugins_get_plugins(self):
        """Test case for plugins_get_plugins

        Gets the list and status of all running plugins on the server.  # noqa: E501
        """
        pass

    def test_plugins_post_plugin_config(self):
        """Test case for plugins_post_plugin_config

        Sets the configuration options for the given plugin.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
