# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.log_api import LogApi  # noqa: E501
from ecoserver.rest import ApiException


class TestLogApi(unittest.TestCase):
    """LogApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.log_api.LogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_log_get_all_logs(self):
        """Test case for log_get_all_logs

        Retrieves a list of all log files on the server.  # noqa: E501
        """
        pass

    def test_log_get_category_logs(self):
        """Test case for log_get_category_logs

        Retrieves a list of all log files in the requested category subfolder if it exists.  # noqa: E501
        """
        pass

    def test_log_get_log_file(self):
        """Test case for log_get_log_file

        Streams a log file over HTTP/HTTPS to a client.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
