# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ecoserver
from ecoserver.api.root_api import RootApi  # noqa: E501
from ecoserver.rest import ApiException


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self):
        self.api = ecoserver.api.root_api.RootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_front_page(self):
        """Test case for root_front_page

        """
        pass

    def test_root_get_admins(self):
        """Test case for root_get_admins

        Returns the server's configured administrative users.  # noqa: E501
        """
        pass

    def test_root_get_info(self):
        """Test case for root_get_info

        """
        pass

    def test_root_is_admin(self):
        """Test case for root_is_admin

        Return if the user is an admin and authentication is required.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
