# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoSharedMathRay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first_pos': 'EcoSharedMathVector3i',
        'first_ray': 'EcoSharedMathRay'
    }

    attribute_map = {
        'first_pos': 'firstPos',
        'first_ray': 'firstRay'
    }

    def __init__(self, first_pos=None, first_ray=None, _configuration=None):  # noqa: E501
        """EcoSharedMathRay - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._first_pos = None
        self._first_ray = None
        self.discriminator = None

        if first_pos is not None:
            self.first_pos = first_pos
        if first_ray is not None:
            self.first_ray = first_ray

    @property
    def first_pos(self):
        """Gets the first_pos of this EcoSharedMathRay.  # noqa: E501


        :return: The first_pos of this EcoSharedMathRay.  # noqa: E501
        :rtype: EcoSharedMathVector3i
        """
        return self._first_pos

    @first_pos.setter
    def first_pos(self, first_pos):
        """Sets the first_pos of this EcoSharedMathRay.


        :param first_pos: The first_pos of this EcoSharedMathRay.  # noqa: E501
        :type: EcoSharedMathVector3i
        """

        self._first_pos = first_pos

    @property
    def first_ray(self):
        """Gets the first_ray of this EcoSharedMathRay.  # noqa: E501


        :return: The first_ray of this EcoSharedMathRay.  # noqa: E501
        :rtype: EcoSharedMathRay
        """
        return self._first_ray

    @first_ray.setter
    def first_ray(self, first_ray):
        """Sets the first_ray of this EcoSharedMathRay.


        :param first_ray: The first_ray of this EcoSharedMathRay.  # noqa: E501
        :type: EcoSharedMathRay
        """

        self._first_ray = first_ray

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoSharedMathRay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoSharedMathRay):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoSharedMathRay):
            return True

        return self.to_dict() != other.to_dict()
