# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoWebServerDataTransferObjectsEntityDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position': 'SystemNumericsVector3',
        'entity_type': 'str'
    }

    attribute_map = {
        'position': 'position',
        'entity_type': 'entityType'
    }

    def __init__(self, position=None, entity_type=None, _configuration=None):  # noqa: E501
        """EcoWebServerDataTransferObjectsEntityDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._position = None
        self._entity_type = None
        self.discriminator = None

        if position is not None:
            self.position = position
        if entity_type is not None:
            self.entity_type = entity_type

    @property
    def position(self):
        """Gets the position of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501


        :return: The position of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501
        :rtype: SystemNumericsVector3
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this EcoWebServerDataTransferObjectsEntityDTO.


        :param position: The position of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501
        :type: SystemNumericsVector3
        """

        self._position = position

    @property
    def entity_type(self):
        """Gets the entity_type of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501


        :return: The entity_type of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this EcoWebServerDataTransferObjectsEntityDTO.


        :param entity_type: The entity_type of this EcoWebServerDataTransferObjectsEntityDTO.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoWebServerDataTransferObjectsEntityDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsEntityDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsEntityDTO):
            return True

        return self.to_dict() != other.to_dict()
