# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoWebServerDataTransferObjectsFrontPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'info': 'EcoSharedNetworkingServerInfo',
        'graphs': 'list[EcoStatsNamedGraph]'
    }

    attribute_map = {
        'info': 'info',
        'graphs': 'graphs'
    }

    def __init__(self, info=None, graphs=None, _configuration=None):  # noqa: E501
        """EcoWebServerDataTransferObjectsFrontPage - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._info = None
        self._graphs = None
        self.discriminator = None

        if info is not None:
            self.info = info
        if graphs is not None:
            self.graphs = graphs

    @property
    def info(self):
        """Gets the info of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501


        :return: The info of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501
        :rtype: EcoSharedNetworkingServerInfo
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this EcoWebServerDataTransferObjectsFrontPage.


        :param info: The info of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501
        :type: EcoSharedNetworkingServerInfo
        """

        self._info = info

    @property
    def graphs(self):
        """Gets the graphs of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501


        :return: The graphs of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501
        :rtype: list[EcoStatsNamedGraph]
        """
        return self._graphs

    @graphs.setter
    def graphs(self, graphs):
        """Sets the graphs of this EcoWebServerDataTransferObjectsFrontPage.


        :param graphs: The graphs of this EcoWebServerDataTransferObjectsFrontPage.  # noqa: E501
        :type: list[EcoStatsNamedGraph]
        """

        self._graphs = graphs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoWebServerDataTransferObjectsFrontPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsFrontPage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsFrontPage):
            return True

        return self.to_dict() != other.to_dict()
