# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoSharedLocalizationLocString(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'not_translated': 'str',
        'inlinable': 'bool',
        'length': 'int'
    }

    attribute_map = {
        'not_translated': 'notTranslated',
        'inlinable': 'inlinable',
        'length': 'length'
    }

    def __init__(self, not_translated=None, inlinable=None, length=None, _configuration=None):  # noqa: E501
        """EcoSharedLocalizationLocString - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._not_translated = None
        self._inlinable = None
        self._length = None
        self.discriminator = None

        if not_translated is not None:
            self.not_translated = not_translated
        if inlinable is not None:
            self.inlinable = inlinable
        if length is not None:
            self.length = length

    @property
    def not_translated(self):
        """Gets the not_translated of this EcoSharedLocalizationLocString.  # noqa: E501


        :return: The not_translated of this EcoSharedLocalizationLocString.  # noqa: E501
        :rtype: str
        """
        return self._not_translated

    @not_translated.setter
    def not_translated(self, not_translated):
        """Sets the not_translated of this EcoSharedLocalizationLocString.


        :param not_translated: The not_translated of this EcoSharedLocalizationLocString.  # noqa: E501
        :type: str
        """

        self._not_translated = not_translated

    @property
    def inlinable(self):
        """Gets the inlinable of this EcoSharedLocalizationLocString.  # noqa: E501


        :return: The inlinable of this EcoSharedLocalizationLocString.  # noqa: E501
        :rtype: bool
        """
        return self._inlinable

    @inlinable.setter
    def inlinable(self, inlinable):
        """Sets the inlinable of this EcoSharedLocalizationLocString.


        :param inlinable: The inlinable of this EcoSharedLocalizationLocString.  # noqa: E501
        :type: bool
        """

        self._inlinable = inlinable

    @property
    def length(self):
        """Gets the length of this EcoSharedLocalizationLocString.  # noqa: E501


        :return: The length of this EcoSharedLocalizationLocString.  # noqa: E501
        :rtype: int
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this EcoSharedLocalizationLocString.


        :param length: The length of this EcoSharedLocalizationLocString.  # noqa: E501
        :type: int
        """

        self._length = length

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoSharedLocalizationLocString, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoSharedLocalizationLocString):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoSharedLocalizationLocString):
            return True

        return self.to_dict() != other.to_dict()
