# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoStatsGraph(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keys': 'list[EcoStatsKey]',
        'time_min': 'float',
        'time_max': 'float'
    }

    attribute_map = {
        'keys': 'keys',
        'time_min': 'timeMin',
        'time_max': 'timeMax'
    }

    def __init__(self, keys=None, time_min=None, time_max=None, _configuration=None):  # noqa: E501
        """EcoStatsGraph - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._keys = None
        self._time_min = None
        self._time_max = None
        self.discriminator = None

        if keys is not None:
            self.keys = keys
        if time_min is not None:
            self.time_min = time_min
        if time_max is not None:
            self.time_max = time_max

    @property
    def keys(self):
        """Gets the keys of this EcoStatsGraph.  # noqa: E501


        :return: The keys of this EcoStatsGraph.  # noqa: E501
        :rtype: list[EcoStatsKey]
        """
        return self._keys

    @keys.setter
    def keys(self, keys):
        """Sets the keys of this EcoStatsGraph.


        :param keys: The keys of this EcoStatsGraph.  # noqa: E501
        :type: list[EcoStatsKey]
        """

        self._keys = keys

    @property
    def time_min(self):
        """Gets the time_min of this EcoStatsGraph.  # noqa: E501


        :return: The time_min of this EcoStatsGraph.  # noqa: E501
        :rtype: float
        """
        return self._time_min

    @time_min.setter
    def time_min(self, time_min):
        """Sets the time_min of this EcoStatsGraph.


        :param time_min: The time_min of this EcoStatsGraph.  # noqa: E501
        :type: float
        """

        self._time_min = time_min

    @property
    def time_max(self):
        """Gets the time_max of this EcoStatsGraph.  # noqa: E501


        :return: The time_max of this EcoStatsGraph.  # noqa: E501
        :rtype: float
        """
        return self._time_max

    @time_max.setter
    def time_max(self, time_max):
        """Sets the time_max of this EcoStatsGraph.


        :param time_max: The time_max of this EcoStatsGraph.  # noqa: E501
        :type: float
        """

        self._time_max = time_max

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoStatsGraph, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoStatsGraph):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoStatsGraph):
            return True

        return self.to_dict() != other.to_dict()
