# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoWebServerDataTransferObjectsUserDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'slg_id': 'str',
        'steam_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'slg_id': 'slgId',
        'steam_id': 'steamId'
    }

    def __init__(self, name=None, slg_id=None, steam_id=None, _configuration=None):  # noqa: E501
        """EcoWebServerDataTransferObjectsUserDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._slg_id = None
        self._steam_id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if slg_id is not None:
            self.slg_id = slg_id
        if steam_id is not None:
            self.steam_id = steam_id

    @property
    def name(self):
        """Gets the name of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501


        :return: The name of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EcoWebServerDataTransferObjectsUserDTO.


        :param name: The name of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def slg_id(self):
        """Gets the slg_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501


        :return: The slg_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :rtype: str
        """
        return self._slg_id

    @slg_id.setter
    def slg_id(self, slg_id):
        """Sets the slg_id of this EcoWebServerDataTransferObjectsUserDTO.


        :param slg_id: The slg_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :type: str
        """

        self._slg_id = slg_id

    @property
    def steam_id(self):
        """Gets the steam_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501


        :return: The steam_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :rtype: str
        """
        return self._steam_id

    @steam_id.setter
    def steam_id(self, steam_id):
        """Sets the steam_id of this EcoWebServerDataTransferObjectsUserDTO.


        :param steam_id: The steam_id of this EcoWebServerDataTransferObjectsUserDTO.  # noqa: E501
        :type: str
        """

        self._steam_id = steam_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoWebServerDataTransferObjectsUserDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsUserDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsUserDTO):
            return True

        return self.to_dict() != other.to_dict()
