# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoWebServerDataTransferObjectsDistrictDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'r': 'int',
        'g': 'int',
        'b': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'r': 'r',
        'g': 'g',
        'b': 'b'
    }

    def __init__(self, id=None, name=None, r=None, g=None, b=None, _configuration=None):  # noqa: E501
        """EcoWebServerDataTransferObjectsDistrictDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._r = None
        self._g = None
        self._b = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if r is not None:
            self.r = r
        if g is not None:
            self.g = g
        if b is not None:
            self.b = b

    @property
    def id(self):
        """Gets the id of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501


        :return: The id of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EcoWebServerDataTransferObjectsDistrictDTO.


        :param id: The id of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501


        :return: The name of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EcoWebServerDataTransferObjectsDistrictDTO.


        :param name: The name of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def r(self):
        """Gets the r of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501


        :return: The r of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :rtype: int
        """
        return self._r

    @r.setter
    def r(self, r):
        """Sets the r of this EcoWebServerDataTransferObjectsDistrictDTO.


        :param r: The r of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :type: int
        """

        self._r = r

    @property
    def g(self):
        """Gets the g of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501


        :return: The g of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :rtype: int
        """
        return self._g

    @g.setter
    def g(self, g):
        """Sets the g of this EcoWebServerDataTransferObjectsDistrictDTO.


        :param g: The g of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :type: int
        """

        self._g = g

    @property
    def b(self):
        """Gets the b of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501


        :return: The b of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :rtype: int
        """
        return self._b

    @b.setter
    def b(self, b):
        """Sets the b of this EcoWebServerDataTransferObjectsDistrictDTO.


        :param b: The b of this EcoWebServerDataTransferObjectsDistrictDTO.  # noqa: E501
        :type: int
        """

        self._b = b

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoWebServerDataTransferObjectsDistrictDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsDistrictDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsDistrictDTO):
            return True

        return self.to_dict() != other.to_dict()
