# coding: utf-8

"""
    Eco Game API

    First API draft for Eco. Heavy work in progress and subject to changes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from ecoserver.configuration import Configuration


class EcoWebServerDataTransferObjectsDistrictMapDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'district_metadata': 'list[EcoWebServerDataTransferObjectsDistrictDTO]',
        'district_map': 'str'
    }

    attribute_map = {
        'district_metadata': 'districtMetadata',
        'district_map': 'districtMap'
    }

    def __init__(self, district_metadata=None, district_map=None, _configuration=None):  # noqa: E501
        """EcoWebServerDataTransferObjectsDistrictMapDTO - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._district_metadata = None
        self._district_map = None
        self.discriminator = None

        if district_metadata is not None:
            self.district_metadata = district_metadata
        if district_map is not None:
            self.district_map = district_map

    @property
    def district_metadata(self):
        """Gets the district_metadata of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501


        :return: The district_metadata of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501
        :rtype: list[EcoWebServerDataTransferObjectsDistrictDTO]
        """
        return self._district_metadata

    @district_metadata.setter
    def district_metadata(self, district_metadata):
        """Sets the district_metadata of this EcoWebServerDataTransferObjectsDistrictMapDTO.


        :param district_metadata: The district_metadata of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501
        :type: list[EcoWebServerDataTransferObjectsDistrictDTO]
        """

        self._district_metadata = district_metadata

    @property
    def district_map(self):
        """Gets the district_map of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501


        :return: The district_map of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501
        :rtype: str
        """
        return self._district_map

    @district_map.setter
    def district_map(self, district_map):
        """Sets the district_map of this EcoWebServerDataTransferObjectsDistrictMapDTO.


        :param district_map: The district_map of this EcoWebServerDataTransferObjectsDistrictMapDTO.  # noqa: E501
        :type: str
        """

        self._district_map = district_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EcoWebServerDataTransferObjectsDistrictMapDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsDistrictMapDTO):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EcoWebServerDataTransferObjectsDistrictMapDTO):
            return True

        return self.to_dict() != other.to_dict()
